// Devanagari names for the districts that reach an orange or red warning in the demo run, and the
// rest of Kerala. Other districts keep their English name in Hindi messages.

const HINDI_NAMES = {
  'alappuzha-kerala': 'आलप्पुझा',
  'balangir-odisha': 'बलांगीर',
  'balod-chhattisgarh': 'बालोद',
  'boudh-odisha': 'बौद्ध',
  'dadra-and-nagar-haveli-dadra-and-nagar-haveli-and-daman-and-diu': 'दादरा और नगर हवेली',
  'dakshina-kannada-karnataka': 'दक्षिण कन्नड़',
  'dhamtari-chhattisgarh': 'धमतरी',
  'durg-chhattisgarh': 'दुर्ग',
  'ernakulam-kerala': 'एर्णाकुलम',
  'gajapati-odisha': 'गजपति',
  'ganjam-odisha': 'गंजाम',
  'gariaband-chhattisgarh': 'गरियाबंद',
  'gondia-maharashtra': 'गोंदिया',
  'idukki-kerala': 'इडुक्की',
  'kalahandi-odisha': 'कालाहांडी',
  'kandhamal-odisha': 'कंधमाल',
  'kannur-kerala': 'कन्नूर',
  'kasaragod-kerala': 'कासरगोड',
  'kodagu-karnataka': 'कोडगु',
  'kollam-kerala': 'कोल्लम',
  'kondagaon-chhattisgarh': 'कोंडागांव',
  'kottayam-kerala': 'कोट्टयम',
  'kozhikode-kerala': 'कोझिकोड',
  'mahe-puducherry': 'माहे',
  'malappuram-kerala': 'मलप्पुरम',
  'mumbai-maharashtra': 'मुंबई',
  'nabarangapur-odisha': 'नबरंगपुर',
  'north-goa-goa': 'उत्तर गोवा',
  'nuapada-odisha': 'नुआपाड़ा',
  'palakkad-kerala': 'पालक्काड',
  'palghar-maharashtra': 'पालघर',
  'pathanamthitta-kerala': 'पत्तनमतिट्टा',
  'raigad-maharashtra': 'रायगड',
  'rajnandgaon-chhattisgarh': 'राजनांदगांव',
  'ratnagiri-maharashtra': 'रत्नागिरी',
  'rayagada-odisha': 'रायगड़ा',
  'sindhudurg-maharashtra': 'सिंधुदुर्ग',
  'south-goa-goa': 'दक्षिण गोवा',
  'srikakulam-andhra-pradesh': 'श्रीकाकुलम',
  'thane-maharashtra': 'ठाणे',
  'thiruvananthapuram-kerala': 'तिरुवनंतपुरम',
  'thrissur-kerala': 'त्रिशूर',
  'udupi-karnataka': 'उडुपी',
  'uttar-bastar-kanker-chhattisgarh': 'उत्तर बस्तर कांकेर',
  'wayanad-kerala': 'वायनाड',
};

/** The district's name in Devanagari, or its English name when none is listed. */
export const hindiName = (id, name) => HINDI_NAMES[id] ?? name;
